version: "3"
services:
  vivi-back:
    ports:
      - "4000:4000"
    restart: always
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - NODE_ENV=docker
  db:
    image: mysql:8.0
    volumes:
      - ./data:/var/lib/mysql
    # ports:
      # - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: liaotingwei
      MYSQL_DATABASE: manage
    restart: always
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 3s
            retries: 10
